### ISSUE TITLE
App Crash on Ios when using MergeResourceDictionary

### ISSUE THREAD

**Issue by nhdanh** [monetelli/XF_FoodApp#1]
I create a app using your styles. I have a problem with MergeResourceDictionary. My app crashed on Ios. Android still Ok. When I remove MergeResourceDictionary and copy all code to file whitetheme.xaml. My app not crash on all version. What's problems with MergeResourceDictionary on Ios ?

**Comment by danielmonettelli** [comment]
Hello @nhdanh, in this application I have not had those problems, send me a capture or the path of your project to verify the problem and solve it.
